---
apiVersion: dns.loredns.k8s.lavieri.dev/v1
kind: Zone
metadata:
  name: otel-trivago
spec:
  name: otel-trivago.k8s.local
---
apiVersion: dns.loredns.k8s.lavieri.dev/v1
kind: Record
metadata:
  name: reservation
spec:
  zone: otel-trivago.k8s.local
  name: reservation
  type: A
  value: 192.168.1.13
---
apiVersion: dns.loredns.k8s.lavieri.dev/v1
kind: Record
metadata:
  name: room
spec:
  zone: otel-trivago.k8s.local
  name: room
  type: A
  value: 192.168.1.13
---
apiVersion: dns.loredns.k8s.lavieri.dev/v1
kind: Record
metadata:
  name: stay-otel-trivago
spec:
  zone: otel-trivago.k8s.local
  name: stay
  type: A
  value: 192.168.1.13
---
apiVersion: dns.loredns.k8s.lavieri.dev/v1
kind: Record
metadata:
  name: frontdesk-otel-trivago
spec:
  zone: otel-trivago.k8s.local
  name: frontdesk
  type: A
  value: 192.168.1.13
---
