labels:
  - includeTemplates: true
    pairs:
      otel-trivago/env: local

resources:
  - ../../base
  - certs.yaml
  - svc-jaeger.yaml
  - svc-prom.yaml

patchesStrategicMerge:
  - ingress.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: reservation.otel-trivago.local
      - op: replace
        path: /spec/rules/1/host
        value: room.otel-trivago.local
      - op: replace
        path: /spec/rules/2/host
        value: stay.otel-trivago.local
      - op: replace
        path: /spec/rules/3/host
        value: frontdesk.otel-trivago.local
    target:
      kind: Ingress
      name: grpc
