---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-trivago-local
labels:
  - includeTemplates: true
    pairs:
      otel-trivago/env: "local"

resources:
  - ns.yaml
  - ../../base
  - cert.yaml
  - svc-jaeger.yaml
  - svc-echo.yaml
  - svc-prom.yaml

patchesStrategicMerge:
  - ingress.yaml

patches:
  - target:
      kind: Ingress
      name: grpc
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: reservation.otel-trivago.local
      - op: replace
        path: /spec/rules/1/host
        value: room.otel-trivago.local
      - op: replace
        path: /spec/rules/2/host
        value: stay.otel-trivago.local
      - op: replace
        path: /spec/rules/3/host
        value: frontdesk.otel-trivago.local

secretGenerator: []
